### ISSUE TITLE
Default Events view to current week

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance-ios#39]
We might be able to make use of this helper method to clean up the groupEventByWeeks method https://github.com/the-blue-alliance/the-blue-alliance-android/blob/c4948c3a560e3b73833197b92d24295027004afe/android/src/main/java/com/thebluealliance/androidclient/helpers/EventHelper.java#L98

**Comment by ZachOrr** [comment]
Yeah, we should be able to determine an event's week independent of other events going on, unlike we do now

https://github.com/the-blue-alliance/the-blue-alliance-android/blob/2ddd0dd406e4f56f8749537c5b9e9c5b87c62fc5/android/src/main/java/com/thebluealliance/androidclient/models/Event.java#L315

https://github.com/the-blue-alliance/the-blue-alliance-android/blob/5e184c67936d0032d336e73b1b70a3f73d653404/android/src/main/java/com/thebluealliance/androidclient/Utilities.java#L76

**Comment by phil-lopreiato** [comment]
Here's the place the week is actually set:
https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/fragments/EventsByWeekFragment.java#L175

And this was the fix for the gap issue: https://github.com/the-blue-alliance/the-blue-alliance-android/commit/71afdf328659d68459c48477aa00ecc52f2f986b
