### ISSUE TITLE
UI/UX Update

### ISSUE THREAD

**Issue by kevinbai0** [the-blue-alliance/the-blue-alliance-ios#527]
I love using the app to check scores, events, and stats. However, sometimes it feels cluttered, gets confusing, and it becomes hard to navigate to different areas of the app without losing your current page. For example, #464, #455, and #439 are all UX issues in the app. I'd love to work on a redesign of the app or even just a few pages (I could also implement them as well) if that's something that you guys are looking for right now.

**Comment by ZachOrr** [comment]
Hey @kevinbai0 - you're more than welcome to work on the app! My suggestion would be to either work on existing issues (since they're known improvements we want to make), or come chat with us about what could be better in Slack (you can request an invite via our mailing list https://groups.google.com/forum/#!topic/thebluealliance-developers/-KrhqOSgTcA)

**Comment by kevinbai0** [comment]
Yeah for sure @ZachOrr, I'll work on some existing issues first!

**Comment by ZachOrr** [comment]
#514 is also a good UX issue to look in to

**Comment by ZachOrr** [comment]
I'm going to close this issue out - I'm going through the project and tagging issues that relate to design/ui/ux things so they're easier to find
