### ISSUE TITLE
Watching a match full screen, rotate from portrait to landscape closes video

### ISSUE THREAD

**Issue by mzodun** [the-blue-alliance/the-blue-alliance-ios#858]
**Describe the bug**
When watching a match, in full screen mode, if the phone is rotated from portrait to landscape the video closes and returns to a split screen with the event listed on the left with the right side of the screen blank.

**To Reproduce**
1. Make sure phone is in portrait mode.  Go to 'Week 1 events'
2. Click on 'ISR #1' and then "Matches"
3. Scroll down to 'Quals 6 and click on it'
4. Play the video (this launches to full screen)
5. Rotate phone to landscape mode.  
6. Video stops, you are returned to a split screen of the full event on the left, with the right side of the screen blank.

**Expected behavior**
1. The video should still be full screen and display in landscape mode.
**Screenshots**
Screenshots are attached.

**Your Environment (please complete the following information):**
 - Device: iPhone 11
 - OS: 13.3.1
 - TBA for iOS Version: 2.0.4 (99)

**Additional context**

![IMG_8410](https://user-images.githubusercontent.com/60298249/75395784-1e63a280-58c1-11ea-9721-2cc047e3c0d3.PNG)
![IMG_8411](https://user-images.githubusercontent.com/60298249/75395791-21f72980-58c1-11ea-88a1-4eac0c26c2ed.PNG)

**Comment by ZachOrr** [comment]
[This](https://github.com/the-blue-alliance/the-blue-alliance-ios/blob/82685accb5bc352bc5d79b15126e69dd542b83d7/the-blue-alliance-ios/App%20Delegate/AppDelegate.swift#L491) looks like the problematic LOC. When we're showing a presented full screen controller, that `popToRootViewController` fails. The issue is going to be getting the view hierarchy setup properly to support the split view controller in this situation.

The reason why this isn't breaking for viewing team media is because we're capturing the view controller somewhere by accident 🤦‍♂ 

The other option is to remove the split view controller on iPhone altogether. The delegate methods don't necessarily get called on iPad, since on iPad the split view is never collapsed.
